= Ground truth initialization parameters

All models can optionally consume `osi3::GroundTruth` via an initialization parameter called `OSMPGroundTruthInit`.
Its purpose is to provide the model with a view of the static environment, for example the map, in OSI format.

`OSMPGroundTruthInit` contains all static data encountered by the model during a simulation run, for example, roads.
If it contains dynamic data, for example, moving objects, this data is not used and has no specific semantics.

If the model is instantiated multiple times, it is recommended that all instantiations should receive the exact same content.
This allows a model to do expensive map calculations only once during initialization, and to share the calculated data between multiple instantiations.

**Rules**

* `OSMPGroundTruthInit` shall be encoded as `osi3::GroundTruth`.
* If a model needs ground truth during initialization, it shall have a parameter named `OSMPGroundTruthInit`.
* `OSMPGroundTruthInit` shall be defined as a notional discrete binary input parameter variable, with `@causality="parameter"`, `@variability="fixed"` and `@initial="exact"`.
* The MIME type of the variable shall specify the @type=GroundTruth, e.g. application/x-open-simulation-interface; type=GroundTruth; version=3.3.1.
* `OSMPGroundTruthInit` shall contain all static data encountered by the model during a simulation run.
* If `OSMPGroundTruthInit` contains any dynamic data, it shall not be used.
* The IDs of objects in `OSMPGroundTruthInit` shall be identical to the IDs of the same objects contained in later `OSMPSensorViewIn` or other input data.
* If the model is instantiated multiple times, then all instantiations should receive the exact same content stored in the `OSMPGroundTruthInit` parameter.
*The guaranteed lifetime of the ground truth protocol buffer pointer provided as input to the FMU shall be from the time of the call to `fmi2SetInteger` that provides those values until the end of the following `fmi2ExitInitializationMode` call.
