= Sensor view inputs

Sensor-view inputs are present in sensor models.

The sensor model can rely on the provided buffer remaining valid from the moment it is passed in until the end of the corresponding calculation.
It does not need to copy the contents (zero-copy input).

**Prefix**

Sensor-view inputs shall be named with the following prefix:

[source]
----
OSMPSensorViewIn
----

**Rules**

* Sensor-view data shall be encoded as `osi3::SensorView`.
* If only one sensor-view input is configured, the prefix shall only be `OSMPSensorViewIn`.
* If more than one sensor-view input is configured, the prefix shall be extended by an array index, for example, `OSMPSensorViewIn[1]` and `OSMPSensorViewIn[2]`.
* Array indices shall start at 1 and shall be consecutive.
* Each sensor-view input shall be defined as a notional discrete binary input variable with `@causality="input"` and `@variability="discrete"`.
* The MIME type of the variable shall specify the `@type=SensorView`.
* The guaranteed lifetime of the sensor-view protocol-buffer pointer provided as input to the FMU shall be from the time of the call to `fmi2SetInteger` that provides those values until the end of the following `fmi2DoStep` call.
* The sensor view passed to the model shall contain data as specified by the parameter `OSMPSensorViewInConfiguration`.