= Sensor view outputs

**Prefix**

Sensor view outputs shall be named with the following prefix:

[source]
----
OSMPSensorViewOut
----

**Rules**

* If only one sensor view output is configured, the prefix shall only be `OSMPSensorViewOut`.
* If more than one sensor view output is configured, the prefix shall be extended by an array index, for example, `OSMPSensorViewOut[1]` and `OSMPSensorViewOut[2]`.
* Array indices shall start at 1 and shall be consecutive.
* Each sensor view output shall be defined as a notional discrete binary output variable with `@causality="output"` and `@variability="discrete"`.
* The MIME type of the variable shall specify the `type="SensorView"` as part of the MIME type parameters.
* Sensor view data shall be encoded as `osi3::SensorView`.
* The guaranteed lifetime of the sensor view protocol-buffer pointer provided as output by the FMU shall be from the end of the call to `fmi2DoStep` that calculated this buffer until the beginning of the second `fmi2DoStep` call after that.