= Sensor view outputs

Sensor-view outputs are present in environmental effect models.

The simulation engine can rely on the provided buffer to remain valid from the moment it is passed out until the end of the next co-simulation calculation cycle.
Thus, the simulation engine does not need to copy the contents in that case, corresponding to zero-copy output for the simulation engine at the cost of double buffering for the environmental effect model.
This arrangement is required to support use of the environmental effect model FMUs in simulation engines that have no special support for the protocol buffer pointers.
Using this convention, it is possible to daisy-chain FMUs with protocol buffer inputs and outputs in a normal simulation engine, for example, MATLAB/Simulink, and get valid results.

**Prefix**

Sensor view outputs shall be named with the following prefix:

[source]
----
OSMPSensorViewOut
----

**Rules**

* Sensor-view data shall be encoded as `osi3::SensorView`.
* If only one sensor-view output is configured, the prefix shall only be `OSMPSensorViewOut`.
* If more than one sensor-view output is configured, the prefix shall be extended by an array index, for example, `OSMPSensorViewOut[1]` and `OSMPSensorViewOut[2]`.
* Array indices shall start at 1 and shall be consecutive.
* Each sensor-view output shall be defined as a notional discrete binary output variable with `@causality="output"` and `@variability="discrete"`.
* The MIME type of the variable shall specify the `@type="SensorView"`.
* The guaranteed lifetime of the sensor-view protocol-buffer pointer provided as output by the FMU shall be from the end of the call to `fmi2DoStep` that calculated this buffer until the beginning of the second `fmi2DoStep` call after that.