= Sensor data outputs

ifndef::include-only-once[]
:root-path: ../
include::{root-path}_config.adoc[]
endif::[]

**Prefix**

Sensor data outputs shall be named with the following prefix:

[source,protobuf]
----
OSMPSensorDataOut
----

**Rules**

* If only one sensor data output is configured, the prefix shall only be `OSMPSensorDataOut`.
* If more than one sensor data output is configured, the prefix shall be extended by an array index, for example, `OSMPSensorDataOut[1]` and `OSMPSensorDataOut[2]`.
* Array indices shall start at 1 and shall be consecutive.
* Each sensor data output shall be defined as a notional discrete binary output variable with `@causality="output"` and `@variability="discrete"`.
* The MIME type of the variable shall specify `type="SensorData"` as part of the MIME type parameters.
* Sensor data shall be encoded as `osi3::SensorData`.
* The guaranteed lifetime of the sensor data protocol-buffer pointer provided as output by the FMU shall be from the end of the call to `fmi2DoStep` that calculated this buffer until the beginning of the second `fmi2DoStep` call after that.