= Sensor data inputs

Sensor-data inputs are present in logical models.
The sensor data passed to the model depends on prior models or processes that generated the data.
The exact details of the contents therefore depend on the processing pipeline.

The logical model can rely on the provided buffer remaining valid from the moment it is passed in until the end of the corresponding calculation.
It does not need to copy the contents (zero-copy input).

**Prefix**

Sensor-data inputs shall be named with the following prefix:

[source]
----
OSMPSensorDataIn
----

**Rules**

* Sensor data shall be encoded as `osi3::SensorData`.
* If only one sensor-data input is configured, the prefix shall only be `OSMPSensorDataIn`.
* If more than one sensor-data input is configured, the prefix shall be extended by an array index, for example, `OSMPSensorDataIn[1]` and `OSMPSensorDataIn[2]`.
* Array indices shall start at 1 and shall be consecutive.
* Each sensor-data input shall be defined as a notional discrete binary input variable with `@causality="input"` and `@variability="discrete"`.
* The MIME type of the variable shall specify the `@type="SensorData"`. 
* The guaranteed lifetime of the sensor-data protocol-buffer pointer provided as input to the FMU shall be from the time of the call to `fmi2SetInteger` that provides those values until the end of the following `fmi2DoStep` call.