ifndef::include-only-once[]
:root-path: ../
include::{root-path}_config.adoc[]
endif::[]
= Streaming update inputs

Streaming update inputs are present in streaming update consumer models.
They provide incremental updates of environmental simulation state in a way that is suitable for low latency applications.

**Prefix**

Streaming update inputs shall be named with the following prefix:

[source,protobuf]
----
OSMPStreamingUpdateIn
----

**Rules**

* If only one streaming update input is configured, the prefix shall only be `OSMPStreamingUpdateIn`.
* If more than one streaming update input is configured, the prefix shall be extended by an array index designator, for example `OSMPStreamingUpdateIn[1]` and `OSMPStreamingUpdateIn[2]`.
* Array indices shall start at 1 and shall be consecutive.
* Each streaming update input shall be defined as a notional discrete binary input variable with `@causality="input"` and `@variability="discrete"`.
* The MIME type of the variable shall specify the `type="StreamingUpdate"` as part of the MIME type parameters.
* Streaming updates shall be encoded as `osi3::StreamingUpdate`.
* The guaranteed lifetime of the traffic command protocol-buffer pointer provided as input to the FMU shall be from the time of the call to `fmi2SetInteger` that provides those values until the end of the following `fmi2DoStep` call.
