ifndef::include-only-once[]
:root-path: ../
include::{root-path}_config.adoc[]
endif::[]
= Traffic update outputs

Traffic update outputs are present in traffic participant models.

**Prefix**

Traffic update outputs shall be named with the following prefix:

[source,protobuf]
----
OSMPTrafficUpdateOut
----

**Rules**

* If only one traffic update output is configured, the prefix shall only be `OSMPTrafficUpdateOut`.
* If more than one traffic update output is configured, the prefix shall be extended by an array index, for example `OSMPTrafficUpdateOut[1]` and `OSMPTrafficUpdateOut[2]`.
* Array indices shall start at 1 and shall be consecutive.
* Each traffic update output shall be defined as a notional discrete binary output variable with a `@causality="output"` and a `@variability="discrete"`.
* The MIME type of the variable shall specify the `type=TrafficUpdate` as part of the MIME type parameters.
* Traffic updates shall be encoded as `osi3::TrafficUpdate`.
* The guaranteed lifetime of the traffic update protocol-buffer pointer provided as output by the FMU shall be from the end of the call to `fmi2DoStep` that calculated this buffer until the beginning of the second `fmi2DoStep` call after that.