= Traffic update outputs

Traffic-update outputs are present in traffic participant models.

The simulation engine can rely on the provided buffer to remain valid from the moment it is passed out until the end of the next co-simulation calculation cycle.
Thus, the simulation engine does not need to copy the contents in that case, corresponding to zero-copy output for the simulation engine at the cost of double buffering for the traffic participant model.
This arrangement is required to support use of the traffic participant model FMUs in simulation engines that have no special support for the protocol buffer pointers.
Using this convention, it is possible to daisy-chain FMUs with protocol buffer inputs and outputs in a normal simulation engine, for example, MATLAB/Simulink, and get valid results.

**Prefix**

Traffic update outputs shall be named with the following prefix:

[source]
----
`OSMPTrafficUpdateOut`
----

**Rules**

* Traffic updates shall be encoded as `osi3::TrafficUpdate`.
* If only one traffic-update output is configured, the prefix shall only be `OSMPTrafficUpdateOut`. 
* If more than one traffic-update output is configured, the prefix shall be extended by an array index, for example `OSMPTrafficUpdateOut[1]` and `OSMPTrafficUpdateOut[2]`. 
* Array indices shall start at 1 and shall be consecutive.
* Each traffic-update output shall be defined as a notional discrete binary output variable with a `@causality="output"` and a `@variability="discrete"`.
* The MIME type of the variable shall specify the `@type=TrafficUpdate`.
* The guaranteed lifetime of the traffic-update protocol-buffer pointer provided as output by the FMU shall be from the end of the call to `fmi2DoStep` that calculated this buffer until the beginning of the second `fmi2DoStep` call after that.