= Traffic command update outputs

ifndef::include-only-once[]
:root-path: ../
include::{root-path}_config.adoc[]
endif::[]

Traffic command update outputs are present in traffic participant models.

**Prefix**

Traffic command update outputs shall be named with the following prefix:

[source,protobuf]
----
OSMPTrafficCommandUpdateOut
----

**Rules**

* If only one traffic command update output is configured, the prefix shall only be `OSMPTrafficCommandUpdateOut`.
* If more than one traffic command update output is configured, the prefix shall be extended by an array index, for example `OSMPTrafficCommandUpdateOut[1]` and `OSMPTrafficCommandUpdateOut[2]`.
* Array indices shall start at 1 and shall be consecutive.
* Each traffic command update output shall be defined as a notional discrete binary output variable with a `@causality="output"` and a `@variability="discrete"`.
* The MIME type of the variable shall specify the `type=TrafficCommandUpdate` as part of the MIME type parameters.
* Traffic command updates shall be encoded as `osi3::TrafficCommandUpdate`.
* The guaranteed lifetime of the traffic command update protocol-buffer pointer provided as output by the FMU shall be from the end of the call to `fmi2DoStep` that calculated this buffer until the beginning of the second `fmi2DoStep` call after that.